"""Build the per-video transcripts and the video table from the YouTube playlist.

Inputs (downloaded with yt-dlp, see README):
  materials/playlist.json                 yt-dlp --flat-playlist -J <playlist>
  materials/transcripts/raw/NNN-<id>.en-orig.json3   auto-captions, one file per video
Outputs:
  materials/videos.csv                    index, chapter, video, chapter title, video title, id, duration
  materials/transcripts/CXX-VYY.txt       clean text, one line per ~20 s, "m:ss" local time
  lecture-notes/videos.tex                \\tsvideo{C@V}{id} table read by the preamble (\\ts links)
"""
import csv
import glob
import json
import os

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
MAT = os.path.join(ROOT, 'materials')
LINE_SECONDS = 20

# The playlist titles carry no lecture/part numbers: chapters are by topic (see README).
# chapter -> (title, playlist indices in reading order)
CHAPTERS = {
    1: ('Overview and anatomy of a dynamical system', [1, 2]),
    2: ('Fundamentals: fixed points, linearization, invariant manifolds, bifurcations, chaos', [24]),
    3: ('Simulating continuous and discrete dynamics', [3, 4, 5]),
    4: ('Dynamic mode decomposition', [6, 7, 8, 9]),
    5: ('Sparse identification of nonlinear dynamics', [10, 11]),
    6: ('Koopman spectral analysis', [12, 13, 14, 15, 16]),
    7: ('Koopman observable subspaces and control', [17, 19, 20]),
    8: ('Hankel alternative view of Koopman (HAVOK)', [18, 21, 22, 23]),
}


def mmss(ms):
    s = int(ms // 1000)
    return f'{s // 60}:{s % 60:02d}'


def caption_lines(path):
    """json3 auto-captions -> [(start_ms, text)], words grouped in ~LINE_SECONDS chunks."""
    words = []
    for ev in json.load(open(path, encoding='utf8')).get('events', []):
        for seg in ev.get('segs', []):
            w = seg['utf8'].strip()
            if w:
                words.append((ev['tStartMs'] + seg.get('tOffsetMs', 0), w))
    lines, start, buf = [], None, []
    for t, w in words:
        if start is None:
            start = t
        buf.append(w)
        if t - start >= LINE_SECONDS * 1000:
            lines.append((start, ' '.join(buf)))
            start, buf = None, []
    if buf:
        lines.append((start, ' '.join(buf)))
    return lines


def main():
    entries = json.load(open(os.path.join(MAT, 'playlist.json'), encoding='utf8'))['entries']
    assert len(entries) == 24, len(entries)
    order = [i for _, idx in CHAPTERS.values() for i in idx]
    assert sorted(order) == list(range(1, 25)), order  # every video in exactly one chapter

    rows = []
    for C, (ctitle, idx) in CHAPTERS.items():
        for V, i in enumerate(idx, 1):
            e = entries[i - 1]
            rows.append(dict(index=i, chapter=C, video=V, chapter_title=ctitle,
                             video_title=e['title'].strip(), id=e['id'], duration=int(e['duration'])))

    with open(os.path.join(MAT, 'videos.csv'), 'w', newline='', encoding='utf8') as f:
        w = csv.DictWriter(f, fieldnames=list(rows[0]))
        w.writeheader()
        w.writerows(rows)

    with open(os.path.join(ROOT, 'lecture-notes', 'videos.tex'), 'w', encoding='utf8') as f:
        f.write('% Generated by tools/transcripts.py: YouTube ID of every video (chapter@video)\n')
        for r in rows:
            f.write(f"\\tsvideo{{{r['chapter']}@{r['video']}}}{{{r['id']}}} % {r['video_title']}\n")

    missing = []
    for r in rows:
        raw = glob.glob(os.path.join(MAT, 'transcripts', 'raw', f"{r['index']:03d}-*.json3"))
        if not raw:
            missing.append(r['index'])
            continue
        out = os.path.join(MAT, 'transcripts', f"C{r['chapter']:02d}-V{r['video']:02d}.txt")
        with open(out, 'w', encoding='utf8') as f:
            f.write(f"Ch {r['chapter']}: {r['chapter_title']} | Video {r['video']}: {r['video_title']}"
                    f" | https://youtu.be/{r['id']} | {mmss(r['duration'] * 1000)}\n")
            for t, text in caption_lines(raw[0]):
                f.write(f'{mmss(t)} {text}\n')
    print(f'{len(rows)} videos, {len(rows) - len(missing)} transcripts written'
          + (f', missing: {missing}' if missing else ''))


if __name__ == '__main__':
    main()
